name: "Notification - Create Derp"
description: "Create a Derp notification for a specific team"
inputs:
  prefix:
    description: "Prefix of the Team"
    required: True
  summary:
    description: "Summary of the Issue"
    required: True
  description:
    description: "Description field of the issue"
    required: True
  labels:
    description: "Labels for the issue"
    required: False

outputs:
  derp-key:
    description: The key generated when calling derp
    value: ${{ steps.create_derp.outputs.issue }}

runs:
  using: "composite"
  steps:
    - run: python ${GITHUB_ACTION_PATH}/derp.py --prefix="${{ inputs.prefix }}" --summary="${{ inputs.summary }}" --description="${{ inputs.description }}"
      shell: bash
      id: create_derp
