name: "Notification - Create Derp"
description: "Create a Derp notification for a specific team"
inputs:
  prefix:
    description: "Prefix of the Team"
    required: True
outputs:
  derp-key:
    description: The key generated when calling derp
    value: ${{ steps.create_derp.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - run: python ${GITHUB_ACTION_PATH}/derp.py --prefix="${{ inputs.prefix }}"
      shell: bash
      id: create_derp
