name: Check output of YQ command
on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout matrix repo
        uses: actions/checkout@v4
        
      - name: Check YQ command
#        run: echo "matrix=$(jq -c . < derp/config/matrix.json)" >> $GITHUB_ENV
        run: |
          echo "MATRIX_YAML=$(yq -p yaml -o json -I=0 config/matrix.yaml)" >> $GITHUB_ENV
      - name: Check YQ var
        run: |
          echo $MATRIX_YAML
          echo ${{ fromJson(env.MATRIX_YAML).account }}

      - name: Check JSON command
        run: |
          echo "MATRIX_JSON=$(jq -c . < config/matrix.json)" >> $GITHUB_ENV
      - name: Check YQ var
        run: |
          echo $MATRIX_JSON
          echo ${{ fromJson(env.MATRIX_JSON).account }}

      - name: Check YQ command
#        run: echo "matrix=$(yq -p yaml -o json -I=0 config/matrix.yaml)" >> $GITHUB_ENV
      - name: Check matrix
         run: |
           echo $matrix
           echo ${{ env.matrix }}
