name: Testing stuff

on: [workflow_dispatch, push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myoutput: ${{ steps.step1.outputs.myoutput }}
    
    steps:
    - name: set output
      id: step1
      run: |
        echo "myoutput='hello world'" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: retrieve output
      run: |
        echo ${{ needs.job1.outputs.myoutput }}
