name: Testing stuff

on: [workflow_dispatch, push]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.create-issue.outputs.issue }}
    
    steps:
    - name: checkout code
      uses: actions/checkout@v3 
    - name: set output
      id: create-issue
      working-directory: scripts
      run: |
        python set_env.py

  job2:
    needs: create-issue
    runs-on: ubuntu-latest
    steps:
    - name: retrieve output
      run: |
        echo ${{ steps.create-issue.outputs.issue }}
