name: Testing stuff

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set output
        run: echo "issue=TST-3460" >> "$GITHUB_OUTPUT"
      - name: check output
        run: echo "$GITHUB_OUTPUT"
